# Generated by Django 4.2.4 on 2023-08-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_user_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mention',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
